### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by ziyafenn** [includable/react-native-check-version#2]
Hi guys. Thanks for the awesome library. 

I have no probs with it on iOS, however on Android i'm getting this error:
```
Got version info: 
error: "Invalid Version: //play.google.com/">"
error: "Invalid Version: //play.google.com/">
```

I tried that with debug and release versions.

Is it a bug or i just need to test it on the app download from the market?

Thanks.

**Comment by tschoffelen** [comment]
Can you share a bit more of your code?

Cheers,

Thomas

**Comment by ziyafenn** [comment]
hey @tschoffelen, i used your example:
```
    checkVersion()
      .then(version => {
        console.log("Got version info:", version);
        if (version.needsUpdate) {
             this.setState({ updateNeeded: true, storeURL: version.url })
        }
      })
      .catch(e => {
        // Error - could not get version info for some reason
        console.log("Failed getting version info:", e);
      });
```

`console.log("Got version info:", version);` returns the described error on Android.

On ios all works well.

**Comment by ziyafenn** [comment]
@tschoffelen were you able to replicate this?

**Comment by tschoffelen** [comment]
@ziyafenn Apologies for the slow response. This turned out to be a bug on the server-side, which has just been fixed:

https://github.com/includable/react-native-check-version/commit/c7e6471b0cec9c2dbbbd31e9ddb3a868c688768e
