### ISSUE TITLE
Does this work with internal testing as well.

### ISSUE THREAD

**Issue by Princepal31** [includable/react-native-check-version#41]
I have a app that is still in internal testing and not for public right now will this package work with that as well?

**Comment by arlandantas** [comment]
No, @Princepal31 . This package only works with public published apps (at least for android apps).

**Comment by arlandantas** [comment]
More info in https://github.com/includable/react-native-check-version/issues/14

**Comment by tschoffelen** [comment]
Closing this and leaving #14 open as the reference issue for this question.
