### ISSUE TITLE
[Android] version is null

### ISSUE THREAD

**Issue by dawidzawadzki** [includable/react-native-check-version#43]
Hi, On Android 10 I am getting version null and error "Error: Request failed with status code 403". Adding 'sec-fetch-site': 'same-origin' to headers solves the problem. Could you check it?

**Comment by tschoffelen** [comment]
Thanks! Feel free to open a PR to add this to the library!

**Comment by dawidzawadzki** [comment]
Thanks for your response. I opened PR.
