### ISSUE TITLE
Adding error field to the TS interface

### ISSUE THREAD

**Issue by adamzu** [includable/react-native-check-version#50]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-check-version@1.1.0` for the project I'm working on.

Hi! Just proposing a minor change the to TS interface to help handle errors when the app doesn't exist

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-check-version/index.d.ts b/node_modules/react-native-check-version/index.d.ts
index 20d4295..453f93b 100644
--- a/node_modules/react-native-check-version/index.d.ts
+++ b/node_modules/react-native-check-version/index.d.ts
@@ -21,6 +21,7 @@ export interface CheckVersionResponse {
   bundleId?: string;
   lastChecked?: string;
   country?: string;
+  error?: Error;
 }
 
 declare const checkVersion: (
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tschoffelen** [comment]
Hi! feel free to open a PR for this change, happy to accept.
